// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Pet struct {
	ID   string   `json:"id"`
	Name string   `json:"name"`
	Tags []string `json:"tags,omitempty"`
}

type PetInput struct {
	Name string   `json:"name"`
	Tags []string `json:"tags,omitempty"`
}

type Query struct {
}
